language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
os:
- linux
- osx
osx_image: xcode6.4
dist: trusty
sudo: false

matrix:
  fast_finish: true
  allow_failures:
  - os: osx

install:
- pip install pytest
- python setup.py install

script:
- pytest
