language: python
osx_image: xcode9.4
dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      python: 2.6
      env: TOXENV=py26
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: linux
      python: 3.5
      env: TOXENV=py35
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - os: linux
      python: 3.8
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      env: TOXENV=py26
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - os: windows
      python: 2.6
      env: TOXENV=py26
    - os: windows
      python: 2.7
      env: TOXENV=py27
    - os: windows
      python: 3.5
      env: TOXENV=py35
    - os: windows
      python: 3.6
      env: TOXENV=py36
    - os: windows
      python: 3.7
      env: TOXENV=py37
    - os: windows
      python: 3.8
      env: TOXENV=py38

install:
  - pip install pytest
  - python setup.py install
  - ./.travis-install.sh

script:
  - pytest -v
